---
name: Python testing

on:
  - pull_request

permissions: read-all

jobs:
  test:
    name: test python code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run tox
        run: |
          pip install tox
          tox
